import jsPDF from 'jspdf';
import { type InsertTripPlan } from '../shared/schema';

export async function generatePDF(tripData: InsertTripPlan) {
  const doc = new jsPDF();
  
  // Set up colors
  const primaryColor = '#0066CC';
  //const secondaryColor = '#10B981';
  const textColor = '#374151';
  
  
  // Header
  doc.setFillColor(primaryColor);
  doc.rect(0, 0, 210, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('TripPlan Pro', 20, 20);
  
  doc.setFontSize(14);
  doc.text('Your Complete Trip Plan', 20, 25);
  
  // Reset color for content
  doc.setTextColor(textColor);
  
  let yPosition = 45;
  
  // Trip Overview
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text('Trip Overview', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(12);
  doc.setTextColor(textColor);
  doc.text(`Trip Name: ${tripData.tripName || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Budget: $${tripData.budget?.toLocaleString() || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Start Date: ${tripData.startDate || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`End Date: ${tripData.endDate || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Travelers: ${tripData.travelers} ${tripData.travelers === 1 ? 'person' : 'people'}`, 20, yPosition);
  yPosition += 15;
  
  // Travel Details
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text('Travel Details', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(12);
  doc.setTextColor(textColor);
  doc.text(`From: ${tripData.departureCity || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`To: ${tripData.destinationCity || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Travel Class: ${tripData.travelClass || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Preferred Airline: ${tripData.preferredAirline || 'Any'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Stops: ${tripData.stops || 'Not specified'}`, 20, yPosition);
  yPosition += 15;
  
  // Accommodation
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text('Accommodation', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(12);
  doc.setTextColor(textColor);
  doc.text(`Type: ${tripData.accommodationType || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Star Rating: ${tripData.starRating || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Room Type: ${tripData.roomType || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Check-in Date: ${tripData.checkinDate || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Number of Nights: ${tripData.nights || 'Not specified'}`, 20, yPosition);
  yPosition += 15;
  
  // Activities
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text('Activities & Experiences', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(12);
  doc.setTextColor(textColor);
  
  if (tripData.activityCategories && tripData.activityCategories.length > 0) {
    doc.text('Selected Categories:', 20, yPosition);
    yPosition += 7;
    tripData.activityCategories.forEach((category: any) => {
      doc.text(`• ${category}`, 25, yPosition);
      yPosition += 7;
    });
  } else {
    doc.text('No activities selected', 20, yPosition);
    yPosition += 7;
  }
  
  doc.text(`Activity Budget: ${tripData.activityBudget || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  
  if (tripData.specialRequests) {
    doc.text('Special Requests:', 20, yPosition);
    yPosition += 7;
    const splitText = doc.splitTextToSize(tripData.specialRequests, 170);
    doc.text(splitText, 20, yPosition);
    yPosition += splitText.length * 7;
  }
  
  yPosition += 10;
  
  // Additional Preferences
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text('Additional Preferences', 20, yPosition);
  yPosition += 10;
  
  doc.setFontSize(12);
  doc.setTextColor(textColor);
  doc.text(`Travel Insurance: ${tripData.travelInsurance || 'Not specified'}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Dietary Restrictions: ${tripData.dietaryRestrictions || 'None'}`, 20, yPosition);
  yPosition += 15;
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by viavgo', 20, 280);
  doc.text(new Date().toLocaleDateString(), 150, 280);
  
  // Save the PDF
  doc.save(`${tripData.tripName || 'viaVgo'}.pdf`);
}
